scan:
    base_path: /home/mzk/Development
    indicators:
        - go.mod
        - package.json
        - requirements.txt
        - README.md
        - .git
        - Dockerfile
        - Makefile
    excluded_dirs:
        - node_modules
        - .git
        - dist
        - build
        - vendor
        - target
        - out
        - tmp
        - temp
    max_depth: 3
    min_project_size: 1024
    shortcuts:
        car: CarLogbook
        jda: Junior-Dev-Acceleration
        taqwa: TaqwaBoard
    update_schedule: 0 9 * * *
users:
    allowed_user_ids: []
rate_limit:
    requests_per_minute: 10
